config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  root to: 'pages#home'


  resource :profile, only: [:show]
  resources :bins, only: [:index, :show] do
    resources :reviews, only: [:new, :create, :destroy]
  end

  get '/infos', to: 'pages#infos'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bin.rb
class Bin < ApplicationRecord
  belongs_to :user, optional: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  mount_uploader :photo, PhotoUploader
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :bin
  validates :name, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bins
  has_many :reviews, dependent: :destroy
  mount_uploader :avatar, PhotoUploader

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def default_url_options
  { host: ENV["HOST"] || "localhost:3000" }
  end
end

app/controllers/bins_controller.rb
class BinsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @bins = Bin.all

    @bins = Bin.where(kind: params[:bin_type])
    redirect_to root_path unless params[:bin_type].present?
    # @bins.each do |bin|
    #   @bin.where[kind: params[:bin_type]
    #   end
    #   raise
    @bins = @bins.near(params[:address], 0.6).limit(3) if params[:address].present?

    @markers = @bins.where.not(latitude: nil, longitude: nil).map do |bin|
      {
        lat: bin.latitude,
        lng: bin.longitude,
        # infoWindow: render_to_string(partial: "infowindow", locals: {bin:bin}),
      image_url: helpers.asset_url("pictogr_#{params[:bin_type]}.png")
      }
    end
  end

  def show
    @bin = Bin.find(params[:id])
    @reviews = @bin.reviews
    @review = Review.new

    @marker = {
        # lat: bin.latitude,
        # lng: bin.longitude
      lat: @bin.latitude,
      lng: @bin.longitude,
       image_url: helpers.asset_url('garbage.png')
        # infoWindow: render_to_string(partial: "infowindow", locals: { bin: bin }),
        # image_url: helpers.asset_url('REPLACE_THIS_WITH_YOUR_IMAGE_IN_ASSETS')
      }
  end


  private

  def bin_params
    params.require(:bin).permit(:name, :id, :address, :photo, :bin_type, :user_id)
  end
end

#   def fetch_github_user_data(username)
#   # 1. on construit l'url à partir du username envoyé à la methode
#   custom_url = "https://api.github.com/users/#{username}"
#   # 2. on récupère la réponse de l'API au format JSON
#   json_response    = open(custom_url).read
#   # 3. on parse le json en un format utilisable par Ruby (hash)
#   user_github_data = JSON.parse(json_response)

#   # 4. la methode retourne un hash ne contenant que les datas qui nous intéressent
#   return {
#     login:              user_github_data["login"],
#     avatar_url:         user_github_data["avatar_url"],
#     biography:          user_github_data["bio"], # => pas d'obligation d'avoir le même naming
#     name:               user_github_data["name"],
#     public_repos_count: user_github_data["public_repos"] # => pas d'obligation d'avoir le même naming
#   }


# end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :infos]

  def home
  end

  def infos
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]

  def create
    @bin = Bin.find(params[:bin_id])
    @review = Review.new(review_params)
    @review.bin = @bin
    @review.user = current_user

    if @review.save
      redirect_to bin_path @bin
    else
      redirect_to bin_path @bin
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    # redirect_to bin_path
  end

  def review_params
    params.require(:review).permit(:name, :description, :id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/geocode_helper.rb
module GeocodeHelper
  def geocode(address)
    return if address.nil?
    lat = Geocoder.search(address).first.data["lat"]
    lon = Geocoder.search(address).first.data["lon"]

    [lon, lat]
  end
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/bins/index.html.erb
 <div class="container-index">
  <div class="container-adress-cards col-xl-8 col-lg-8 col-md-8 col-sm-12">
     <div class="map-boutons">
      <div class="title-bin-index">

      <h1 class="around-bin-text">POUBELLES AUTOUR DE VOUS</h1>
      </div>
        <div class="button-container-index">


          <%= link_to bins_path(bin_type: "verre") do %>
            <div class="btn verre non-active <%= params[:bin_type] == "verre" ? "active filter" : nil%>">Verre</div>
          <% end %>

          <%= link_to bins_path(bin_type: "plastique"), class: 'card_link' do %>
            <div class="btn plastique non-active <%= params[:bin_type] == "plastique" ? "active filter" : nil%>">Plastique</div>
          <% end %>

          <%= link_to bins_path(bin_type: "carton"), class: 'card_link' do %>
            <div class="btn carton non-active <%= params[:bin_type] == "carton" ? "active filter" : nil%>">Carton</div>
          <% end %>

          <%= link_to bins_path(bin_type: "menager"), class: 'card_link' do %>
            <div class="btn menager non-active <%= params[:bin_type] == "menager" ? "active filter" : nil%>">Ménager</div>
          <% end %>
        </div>
      </div>

          <div class="container-address-button">
            <div class="address">
              <div class="search-bar">
                <%= form_tag bins_path, method: :get do %>
                  <%= text_field_tag :address,
                      params[:address], id: 'address_user',
                      placeholder: "Saisissez votre adresse", class: "form-control"%>
                  <%=  hidden_field_tag :bin_type, params[:bin_type] %>
               <% end %>
              </div>
            </div>
          </div>

    <% if @bins.present?%>

      <div class="card-maps-container">
        <div class="container">
          <div class="row">
            <% @bins.each do |bin| %>

              <div class="col-sm.col-md.col-lg.col-xl">
                <%= link_to bin_path(bin, address: params[:address]) do %>

                 <div class="card-trip">
                    <div class="poubelle-image"><%= cl_image_tag(bin.photo, gravity: :north, crop: :fill, class: "poubelle-image-cl") %></div>
                    <div class="card-trip-infos">
                      <div class="card-trip-infos-nameaddress">
                        <h2> Poubelle <%= bin.name %></h2>
                        <p><%= (bin.address.split(','))[0] %>,</p>
                        <p><%= (bin.address.split(','))[1] %>.</p>
                      </div>
                      <div class="card-trip-pricing-container">
                        <div class="card-trip-pricing"><%= bin.reviews.length %><i class="far fa-comment comment"></i></div>
                        <h3 class="card-trip-pricing">+ d'infos</h3>
                      </div>

                      <% if bin.user %>
                        <%= cl_image_tag bin.user.avatar, width: 200, heigth: 200, :gravity=>"faces", :crop=>"fill", class:"card-trip-user avatar-bordered" %>
                      <% end %>
                    </div>
                  </div>
                <% end %>
              </div>
            <%end%>
          </div>
        </div>
      </div>

    <% else %>

    <div>
      <div class="button_notfound">
        <%=  link_to bins_path(bin_type: params[:bin_type]) do %>
          <%= image_tag "retour-arrière.png" %>
          <% end  %>
      </div>


      <div class="notfoundcontainer">
        <div class="notfound">
          <h3><strong>Désolé, nous n'avons rien trouvé dans les environs !</strong></h3>
        </div>
      </div>
    </div>

    <% end %>
  </div>

    <div class="map-bin-container-index col-sm-12 col-md-4 col-lg-6 col-xl-5"">
      <div class="map-container">
        <div id="map"
            data-markers="<%= @markers.to_json %>"
            data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
    </div>
</div>

app/views/bins/show.html.erb
<div class="show-content">
  <div class="container-show">
    <div class="header-show">
      <div class="button-retour">
          <%=  link_to bins_path(bin_type: @bin.kind) do %>
          <%= image_tag "retour-arrière.png" %>
          <% end %>
          <div class="badge<%=@bin.kind%> <%= params[:bin_type] == "verre" ? "active filter" : nil%>"><%=@bin.kind%></div>
      </div>

    </div>
  </div>

  <div class="show-container">
  <div class="show-left">
    <div class="bin-card-profil-infos">
      <div class="bin-image" style="background-image: url('<%= cl_image_path @bin.photo %> ')"></div>


        <div class="bin-details">

          <h3><strong>POUBELLE <%= @bin.name %> </strong> </h3>
          <% if params[:address].present? %>
            <div class="maps_instruction" id='instructions'>
            </div>
          <% else %>
              <p> <%= link_to  "Entrez un itinéraire", bins_path(bin_type: @bin.kind)%> </p>
          <% end  %>

        <div class="user_details">

          <div class="profil-bin-elements">
            <p class="menu-profil"><span class="highlighted highlighted-yellow">ADRESSE</span></p>
            <p id="city"><%= (@bin.address.split(','))[0] %> <br> <%= (@bin.address.split(','))[1]%></p>
          </div>

          <div class="profil-bin-elements">
            <p class="menu-profil"><span class="highlighted highlighted-yellow">PROPRIETAIRE</span></p>
            <p id="city"><%= @bin.user.user_name %></p>

          </div>
        </div>
      </div>
    </div>


    <div class="container-show-commentaires">
    <div class="commentaire-show">
      <div class="showing-bin-name">
        <h3 class="highlighted highlighted-yellow">COMMENTAIRES </h3>
      </div>
      <p><button class="btn review-button" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample"> <i class="fas fa-plus"></i>Ajouter</button></p>
    </div>
  </div>

  <div class="reviews-colapse">


  <div class="collapse" id="collapseExample">
     <div class="card card-body collapse-input">
       <%= simple_form_for [@bin, @review] do |f| %> <!-- simple form -->
         <%= f.input :name, label: 'Objet' %>
         <%= f.input :description,  as: :text, label: 'Votre commentaire' %>
         <%= f.submit "Ajouter", class: "btn btn-primary"%>
         <% end %>
     </div>
  </div>


  <div class="reviews">
    <div class="row customer-reviews">
      <div class="col-md-12 column">
        <div class="inner-box">

        <div class="avis_show">
          <% if @bin.reviews.any? %>
          <% @reviews.each do |review|  %>
          <div class="hover_review">
            <div class="user-infos">
            <div class="user-avatar">
                 <%= cl_image_tag review.user.avatar, width: 200, heigth: 200,  :gravity=>"faces", :crop=>"fill", class:"card-trip-user avatar-bordered" %>
               </div>
               <div class="avis_name-user">
                 <div class="avis-user-name">
                   <p><strong><%= review.user.user_name.capitalize %></strong></p>
                 </div>
                 <div class=" avis-review-name">
                   <p><%= review.name %></p>
                 </div>
               </div>
               <div class="avis_date">
                 <div><p><%= review.created_at.strftime('%d/%m/%Y') %></p></div>
               </div>
            </div>
             <div class="descriptif_avis">
               <div><%= review.description %></div>
             </div>
        </div>
          <% end %>
          <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


  </div>

      <div class="map-show-container">
        <div class="map-container-show">
          <div id='my_map'
            data-mapbox-access-token='<%= ENV['MAPBOX_API_KEY'] %>'
            data-start-coordinates="<%= geocode(params[:address]) || geocode(@bin.address) %>"
            data-end-coordinates='<%= geocode(@bin.address) %>'
            data-initial-zoom-level='14'>
          </div>
          <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.53.1/mapbox-gl.js'></script>
        </div>
      </div>
  </div>

 </div>





<%= javascript_pack_tag 'init_mapbox_show' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> Bin here - Triez ou vous vivez, quand vous voullez, sans vous tromper. </title>
    <meta charset="UTF-8">
      <meta charset="utf-8">

    <title><%= meta_title %></title>
      <meta name="description" content="<%= meta_description %>">

      <!-- Facebook Open Graph data -->
      <meta property="og:title" content="<%= meta_title %>" />
      <meta property="og:type" content="website" />
      <meta property="og:url" content="<%= request.original_url %>" />
      <meta property="og:image" content="<%= meta_image %>" />
      <meta property="og:description" content="<%= meta_description %>" />
      <meta property="og:site_name" content="<%= meta_title %>" />

      <!-- Twitter Card data -->
      <meta name="twitter:card" content="summary_large_image">
      <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
      <meta name="twitter:title" content="<%= meta_title %>">
      <meta name="twitter:description" content="<%= meta_description %>">
      <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
      <meta name="twitter:image:src" content="<%= meta_image %>">

      <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
      <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
      <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
      <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
      <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
      <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
      <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
      <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
      <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
      <link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
      <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
      <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
      <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
      <!-- <link rel="manifest" href="/manifest.json"> -->
      <meta name="msapplication-TileColor" content="#ffffff">
      <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
      <meta name="theme-color" content="#ffffff">

      <%= favicon_link_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Bin Here</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <link href="https://fonts.googleapis.com/css?family=Karla|Lato" rel="stylesheet">
    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.53.1/mapbox-gl.css' rel='stylesheet' />
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/offers/show.html.erb
<% content_for :meta_title, "#{@offer.name} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @offer.description %>
<% content_for :meta_image, cl_image_path(@offer.photo.path) %>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0)), url('<%= image_url("home_banner.jpg") %>');">



  <div class="container">
    <div class="banner-box">
      <div class="title-container">
        <div class= "title">
          <h1 id="name"> <strong> </strong> </h1>
          <h1 id="name2" > <strong></strong> </h1>
          </div>
          <div>
           <p id="call-to-action"> Trouvez où jeter <br></p><span class="lighted lighted-yellow">vos déchets !</span>
            <p id="slogan">
              Bin here est une application de géolocalisation des poubelles. Choisissez votre déchet et nous vous trouvons les poubelles appropriées autour de vous.
             <!--  Triez où vous vivez,<br>
             quand vous voulez,<br>
             sans vous tromper. --></p>
          </div>
        </div>

          <!-- <p> Choisissez un déchet : </p> -->
          <div class="cards-homepage">

              <%= link_to bins_path(bin_type: "verre") do %>
              <div class="card-background-homepage" id="verre" >
                <div class="card-category-homepage" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url('<%= image_url("picto_verre-copie.png") %>');">
                </div>
                  <div class="card-name-homepage">
                    <h5 id="type-verre"> Verre </h5>
                  </div>
              </div>

              <% end %>

              <%= link_to bins_path(bin_type: "plastique"), class: 'card_link' do %>
              <div class="card-background-homepage" id="plastique" >
                <div class="card-category-homepage" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url('<%= image_url("picto_plastique-copie.png") %>');">
                </div>
                <div class="card-name-homepage">
                  <h5 id="type-plastique"> Plastique </h5>
                </div>
              </div>
              <% end %>

              <%= link_to bins_path(bin_type: 'carton'), class: 'card_link' do %>
              <div class="card-background-homepage" id="carton" >
                <div class="card-category-homepage" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url('<%= image_url("picto_carton-copie.png") %>');">
                </div>
                <div class="card-name-homepage">
                  <h5 id="type-carton"> Carton </h5>
                </div>
              </div>
              <% end %>

              <%= link_to bins_path(bin_type: "menager"), class: 'card_link' do %>
              <div class="card-background-homepage" id="menagere" >
                 <div class="card-category-homepage" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url('<%= image_url("picto_menager-copie.png") %>');">
                </div>
                <div class="card-name-homepage">
                  <h5 id="type-menagere"> Poubelles ménagères </h5>
                </div>
              </div>
              <% end %>

            </div>
        </div>
    </div>
</div>
</div>

app/views/pages/infos.html.erb
<h1 class="bin_name"> <span class="highlighted highlighted-yellow"> Informations sur le tri à Nantes </span> </h1>
<div class="info-trisac">
  <br>
  <p> <strong> Le dispositif Tri'Sac, qu'est ce que c'est? </strong>

  <br>
  <br>
  Le dispositif de collecte des déchets ménagers « Tri’Sac » est une première en France. Nantes Métropole a adopté ce système de collecte, sur le territoire de la ville de Nantes, pour développer le tri sélectif en milieu urbain (75 % d’habitat vertical à Nantes).
  <br>
  <br>
  Depuis septembre 2013, l’ensemble des habitants de l’agglomération bénéficie ainsi d’un système de collecte sélective (bacs jaunes, sacs jaunes ou Tri’Sac).
  <br>
   <br>
  <strong> Comment fonctionne le dispositif? </strong>
  <br>
   <br>
  Les Nantais trient les déchets grâce à deux sacs de couleurs : jaune pour les déchets recyclables (emballages hors verre, papier, carton en mélange) et bleu pour les non recyclables. Les sacs sont ensuite déposés dans le conteneur habituel puis collectés par le même véhicule et acheminés au centre de séparation. Sur place, les sacs sont séparés par couleur grâce au lecteur optique : les sacs jaunes sont acheminés vers le centre de tri pour le recyclage et les sacs bleus vers l’usine d’incinération Alcéa pour une valorisation énergétique.
  <br>
   <br>
  <strong> Les consignes : </strong>
  <br>
   <br>
  Il est impératif de n'utiliser que les sacs Tri'Sac de deux couleurs : bleu pour les déchets non recyclables, jaune pour les déchets recyclables, et de bien fermer le lien par un double nœud. Le sac jaune et le sac bleu sont à déposer dans votre bac habituel.
  <br>
   <br>
  Dans les sacs jaunes :
  - les papiers, cartons, cartonnettes (briques vides, emballages en carton plat, cartonnettes, papier, journaux, magazines, prospectus...)
  - les bouteilles et les flacons en plastique et leurs bouchons (bouteilles d'eau, de lait, d'huile alimentaire, de soda, flacons de lessive, de savon, de produits d'entretien...)
  - les emballages en métal (barquettes, canettes de soda, boîtes de conserve, bouteilles de sirop, bombes aérosols).
  <br>
   <br>
  Dans les sacs bleus :
  - les déchets ménagers non recyclés.
  Les sacs jaunes et bleus sont ensuite à déposer ensemble dans votre bac habituel.
  Les bouteilles et les bocaux en verre (sans bouchon, ni couvercle) sont à déposer dans les containers habituels.</p>
  <br>
  <br>
  <p> <strong> En bref: </strong> </p>
</div>


<div class="infobox">
    <div class="info-details row">
      <div class="left-col col-sm-6">
        <div class="info-card">
          <%= image_tag "pictogr_verre.png" , class: 'info-picto' %>
          <div class="info-text">
          <h4 id="couleur-poubelle"> Verre - Container vert </h4>
          <p> Il s'agit uniquement des bouteilles, bocaux, le cristal, les flacons, Gobelets, flacons de parfum, bocaux avec une monture métalique, et rien d'autre.</p>
          </div>
        </div>

        <div class="info-card">
          <%= image_tag "pictogr_plastique.png", class: 'info-picto' %>
          <div class="info-text">
          <h4 id="couleur-poubelle"> Plastique - Sac jaune </h4>
          <p>  Il s’agit des bouteilles et flacons en plastique, des  annuaire, baril de lessive, barquette aluminium, bouteille d'huile plastique, bouteille en plastique, bouteille produit ménager vide, brique alimentaire, cahier, carton, flacon produit ménager vide, flacon en plastique.</p>
          </div>
        </div>
      </div>

      <div class="right-col col-sm-6">
        <div class="info-card">
          <%= image_tag "pictogr_carton.png", class: 'info-picto' %>
          <div class="info-text">
          <h4 id="couleur-poubelle"> Carton - Sac jaune </h4>
          <p> Il s’agit des papiers, des cartons et briques alimentaires, annuaire, baril de lessive, barquette aluminium, boîte de conserve, boîte à oeufs en carton, cahier, carton, enveloppe,livre, magazine, revue, papier, sac en papier… </p>
          </div>
        </div>

        <div class="info-card lower-text-info">
          <%= image_tag "pictogr_menager.png", class: 'info-picto' %>
          <div class="info-text">
          <h4 id="couleur-poubelle"> Ordures ménagères - Sac bleue </h4>
          <p> Il s’agit des déchets non dangereux et non recyclables qui rentrent facilement dans votre bac. Ils ne sont pas issus d’activités spécifiques (ex : un matériau ou un objet issus de la déconstruction, de la mécanique…).</p>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

<div class="logo_and_title">
  <div  class="logo">
    <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logoBINHERE.png" %>
    <% end %>
  </div>
  <%= link_to root_path, class: "navbar-brand navbar-binhere" do %>
  <div class="title_navbar">
    <h3 style="color: #EEB111; font-family: poppins"><strong>BIN</strong><span style="color: black;">here?</span></h3>
    <% end %>
  </div>
</div>





  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item lien-navbar">
          <%= link_to "Infos tri", infos_path, class: "nav-link" %>
        </li>

      <li class="nav-item lien-navbar">
        <%= link_to "A proximité", bins_path(bin_type: "verre") , class: "nav-link lien-navbar" %>
      </li>

      <% if user_signed_in? %>
          <li class="nav-item dropdownnavbar">
          <%= cl_image_tag current_user.avatar, gravity: :north, crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Mon profil", profile_path , class: "dropdown-item" %>

            <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Se connecter", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>